version: '3'

services:
  nginx:
    # dockerhub에서 가져와서 사용할 이미지
    image: nginx:1.25.0
    ports:
      # 호스트머신포트(로컬):컨테이너포트
      - 8000:80
    volumes:
      # 로컬의 src폴더를 컨테이너의 /var/www/html와 연동
      # nginx의 루트폴더가 된다. 즉 src폴더 내부의 index.php가 8000포트시 표시되게 된다
      - ./src:/var/www/html
      # 로컬의 docker/nginx폴더를 컨테이너의 /etc/nginx/conf.d와 연동
      # nginx의 환경설정파일
      - ./docker/nginx:/etc/nginx/conf.d
    # 서비스 의존성 설정
    depends_on:
      - app
  # PHP-FPM의 설정
  app:
    # DockerFile을 이용해서 커스텀이미지를 생성한다
    build:
      # Dockerfile을 저장할 로컬 경로
      context: ./docker/php
      # Dockerfile의 파일명
      dockerfile: Dockerfile
    volumes:
      # 로컬의 src폴더를 컨테이너의 /var/www/html에 연동
      # nginx의 루트폴더가 된다
     - ./src:/var/www/html   
    environment:
      OAUTH2_CLIENT_ID: ${OAUTH2_CLIENT_ID}
      OAUTH2_CLIENT_SECRET: ${OAUTH2_CLIENT_SECRET}